In [1]:
import pandas as pd
import json
import itertools
import numpy as np
from pulp import *

In [2]:
# dataset
optilandia_links=pd.read_csv("/home/actserv/Documents/SaO_Optilandia_dataset/SaO_Optilandia_links.csv")
optilandia_locations=pd.read_csv("/home/actserv/Documents/SaO_Optilandia_dataset/SaO_Optilandia_locations.csv")
optilandia_example_sol=pd.read_json("/home/actserv/Documents/SaO_Optilandia_dataset/SaO_Optilandia_example_solution.json")

with open("/home/actserv/Documents/SaO_Optilandia_dataset/SaO_Optilandia_depot_lorries.json") as json_data:
    data = json.load(json_data)

    
optilandia_depots=data

In [3]:
# a list of all the supply nodes

Depots=list(optilandia_depots.keys())

# Creates a dictionary for the number of units of supply for each supply node
supply={}
for i in range(len(Depots)):
    for j in optilandia_depots[Depots[i]]:
        supply.update({j['lorry_id']:j['capacity']})

Depots=list(supply.keys())

In [4]:
# Creates a list of all demand nodes
lpg_customers=optilandia_locations.dropna()
lpg_customers_nodes=list(optilandia_locations.dropna()['id'])

# Creates a dictionary for the number of units of demand for each demand node
demand={}
lpg_customers_nodes=list(optilandia_locations.dropna()['id'])
lpg_customers_capacity=list(lpg_customers['capacity'])
lpg_customers_level=list(lpg_customers['level'])
# demand.update({lpg_customers_nodes:lpg_customers_level})
for a,b in zip(lpg_customers_nodes,lpg_customers_level):
    demand.update({a:b})

In [5]:
# use greedy algorithms to find the shortest routes
depot_locations=optilandia_locations[optilandia_locations['is_depot']==True]
depot_116_shortest_route=[]
depot_124_shortest_route=[]
depot_373_shortest_route=[]
depot_523_shortest_route=[]
depot_passed=[]
depots_coords=[]
depot_ids=[]
lpg_customer_coords=[]
for a,b in zip(depot_locations['x'],depot_locations['y']):
    depots_coords.append(tuple((a,b)))
    depot_ids.append(depot_locations['id'])
for a,b in zip(lpg_customers['x'],lpg_customers['y']):
    lpg_customer_coords.append(tuple((a,b)))
depot_route=depots_coords+lpg_customer_coords
for r in depot_route:
    finish_1=49804.1667
    finish_2=49955.8333
    finish_3=49616.3889
    finish_4=49581.9444
    if finish_1 < r[0] and r[0] < finish_2:
        finish_1=r[1]
        depot_116_shortest_route.append(r)
    elif finish_2 < r[0]:
        finish_2=r[1]
        depot_124_shortest_route.append(r)
    elif finish_3 < r[0] and r[0] < finish_1 and r[0] < finish_2:
        finish_3=r[1]
        depot_373_shortest_route.append(r)
    elif finish_4 > r[0] or finish_4 < r[0] and r[0] < finish_1 and r[0] < finish_2 and r[0] < finish_3:
        finish_4=r[1]
        depot_523_shortest_route.append(r)
    else:
        depot_passed.append(r)

In [6]:
# costs function
depot_116_x=49804.1667
depot_116_y=6253.8889
depot_124_x=49955.8333
depot_124_y=5924.7222
depot_373_x=49616.3889
depot_373_y=5990.2778
depot_523_x=49581.9444
depot_523_y=6226.6667
depot_523_0=[] #5
depot_523_1=[] #5,
depot_523_2=[] #12,
depot_523_3=[] #12,
depot_523_4=[] #22,
depot_124_0=[] #5,
depot_124_1=[] #5,
depot_124_2=[] #5,
depot_124_3=[] #12,
depot_124_4=[] #12,
depot_124_5=[] #12,
depot_124_6=[] #22,
depot_124_7=[] #22,
depot_373_0=[] #5,
depot_373_1=[] #5,
depot_373_2=[] #5,
depot_373_3=[] #12,
depot_373_4=[] #12,
depot_373_5=[] #12,
depot_373_6=[] #12,
depot_373_7=[] #22,
depot_373_8=[] #22,
depot_373_9=[] #22,
depot_116_0=[] #5,
depot_116_1=[] #12
depot_116_df=[]
depot_124_df=[]
depot_373_df=[]
depot_523_df=[]

for i in range(len(depot_116_shortest_route)):
    depot_116_0.append((np.linalg.norm(np.array((depot_116_x,depot_116_y,0))-np.array((depot_116_shortest_route[i][0],depot_116_shortest_route[i][1],0))))*(1.00+5*1.50))
    depot_116_1.append((np.linalg.norm(np.array((depot_116_x,depot_116_y,0))- np.array((depot_116_shortest_route[i][0],depot_116_shortest_route[i][1],0))))*(1.50+12*1.00))
    depot_116_df.append(optilandia_locations[(optilandia_locations['x']==depot_116_shortest_route[i][0]) & (optilandia_locations['y'] == depot_116_shortest_route[i][1])] )
for i in range(len(depot_124_shortest_route)):
    depot_124_0.append((np.linalg.norm(np.array((depot_124_x,depot_124_y,0))-np.array((depot_124_shortest_route[i][0],depot_124_shortest_route[i][1],0))))*(1.00+5*1.50))
    depot_124_1.append((np.linalg.norm(np.array((depot_124_x,depot_124_y,0))-np.array((depot_124_shortest_route[i][0],depot_124_shortest_route[i][1],0))))*(1.00+5*1.50))
    depot_124_2.append((np.linalg.norm(np.array((depot_124_x,depot_124_y,0))-np.array((depot_124_shortest_route[i][0],depot_124_shortest_route[i][1],0))))*(1.00+5*1.50))
    depot_124_3.append((np.linalg.norm(np.array((depot_124_x,depot_124_y,0))- np.array((depot_124_shortest_route[i][0],depot_124_shortest_route[i][1],0))))*(1.50+12*1.00))
    depot_124_4.append((np.linalg.norm(np.array((depot_124_x,depot_124_y,0))- np.array((depot_124_shortest_route[i][0],depot_124_shortest_route[i][1],0))))*(1.50+12*1.00))
    depot_124_5.append((np.linalg.norm(np.array((depot_124_x,depot_124_y,0))- np.array((depot_124_shortest_route[i][0],depot_124_shortest_route[i][1],0))))*(1.50+12*1.00))
    depot_124_6.append((np.linalg.norm(np.array((depot_124_x,depot_124_y,0))- np.array((depot_124_shortest_route[i][0],depot_124_shortest_route[i][1],0))))*(2.00+22*0.50))
    depot_124_7.append((np.linalg.norm(np.array((depot_124_x,depot_124_y,0))- np.array((depot_124_shortest_route[i][0],depot_124_shortest_route[i][1],0))))*(2.00+22*0.50))
    depot_124_df.append(optilandia_locations[(optilandia_locations['x']==depot_124_shortest_route[i][0]) & (optilandia_locations['y'] == depot_124_shortest_route[i][1])] )
for i in range(len(depot_373_shortest_route)):
    depot_373_0.append((np.linalg.norm(np.array((depot_373_x,depot_373_y,0))-np.array((depot_373_shortest_route[i][0],depot_373_shortest_route[i][1],0))))*(1.00+5*1.50))
    depot_373_1.append((np.linalg.norm(np.array((depot_373_x,depot_373_y,0))-np.array((depot_373_shortest_route[i][0],depot_373_shortest_route[i][1],0))))*(1.00+5*1.50))
    depot_373_2.append((np.linalg.norm(np.array((depot_373_x,depot_373_y,0))-np.array((depot_373_shortest_route[i][0],depot_373_shortest_route[i][1],0))))*(1.00+5*1.50))
    depot_373_3.append((np.linalg.norm(np.array((depot_373_x,depot_373_y,0))- np.array((depot_373_shortest_route[i][0],depot_373_shortest_route[i][1],0))))*(1.50+12*1.00))
    depot_373_4.append((np.linalg.norm(np.array((depot_373_x,depot_373_y,0))- np.array((depot_373_shortest_route[i][0],depot_373_shortest_route[i][1],0))))*(1.50+12*1.00))
    depot_373_5.append((np.linalg.norm(np.array((depot_373_x,depot_373_y,0))- np.array((depot_373_shortest_route[i][0],depot_373_shortest_route[i][1],0))))*(1.50+12*1.00))
    depot_373_6.append((np.linalg.norm(np.array((depot_373_x,depot_373_y,0))- np.array((depot_373_shortest_route[i][0],depot_373_shortest_route[i][1],0))))*(1.50+12*0.50))
    depot_373_7.append((np.linalg.norm(np.array((depot_373_x,depot_373_y,0))- np.array((depot_373_shortest_route[i][0],depot_373_shortest_route[i][1],0))))*(2.00+22*0.50))
    depot_373_8.append((np.linalg.norm(np.array((depot_373_x,depot_373_y,0))- np.array((depot_373_shortest_route[i][0],depot_373_shortest_route[i][1],0))))*(2.00+22*0.50))
    depot_373_9.append((np.linalg.norm(np.array((depot_373_x,depot_373_y,0))- np.array((depot_373_shortest_route[i][0],depot_373_shortest_route[i][1],0))))*(2.00+22*0.50))
    depot_373_df.append(optilandia_locations[(optilandia_locations['x']==depot_373_shortest_route[i][0]) & (optilandia_locations['y'] == depot_373_shortest_route[i][1])] )
for i in range(len(depot_523_shortest_route)):
    depot_523_0.append((np.linalg.norm(np.array((depot_523_x,depot_523_y,0))-np.array((depot_523_shortest_route[i][0],depot_523_shortest_route[i][1],0))))*(1.00+5*1.50))
    depot_523_1.append((np.linalg.norm(np.array((depot_523_x,depot_523_y,0))-np.array((depot_523_shortest_route[i][0],depot_523_shortest_route[i][1],0))))*(1.00+5*1.50))
    depot_523_2.append((np.linalg.norm(np.array((depot_523_x,depot_523_y,0))-np.array((depot_523_shortest_route[i][0],depot_523_shortest_route[i][1],0))))*(1.50+12*1.00))
    depot_523_3.append((np.linalg.norm(np.array((depot_523_x,depot_523_y,0))- np.array((depot_523_shortest_route[i][0],depot_523_shortest_route[i][1],0))))*(1.50+12*1.00))
    depot_523_4.append((np.linalg.norm(np.array((depot_523_x,depot_523_y,0))- np.array((depot_523_shortest_route[i][0],depot_523_shortest_route[i][1],0))))*(2.00+22*0.50))
    depot_523_df.append(optilandia_locations[(optilandia_locations['x']==depot_523_shortest_route[i][0]) & (optilandia_locations['y'] == depot_523_shortest_route[i][1])] )

In [7]:
costs=[
    list(np.transpose(depot_116_0)),
    list(np.transpose(depot_116_1)),
    list(np.transpose(depot_124_0)),
    list(np.transpose(depot_124_1)),
    list(np.transpose(depot_124_2)),
    list(np.transpose(depot_124_3)),
    list(np.transpose(depot_124_4)),
    list(np.transpose(depot_124_5)),
    list(np.transpose(depot_124_6)),
    list(np.transpose(depot_124_7)),
    list(np.transpose(depot_373_0)),
    list(np.transpose(depot_373_1)),
    list(np.transpose(depot_373_2)),
    list(np.transpose(depot_373_3)),
    list(np.transpose(depot_373_4)),
    list(np.transpose(depot_373_5)),
    list(np.transpose(depot_373_6)),
    list(np.transpose(depot_373_7)),
    list(np.transpose(depot_373_8)),
    list(np.transpose(depot_373_9)),
    list(np.transpose(depot_523_0)),
    list(np.transpose(depot_523_1)),
    list(np.transpose(depot_523_2)),
    list(np.transpose(depot_523_3)),
    list(np.transpose(depot_523_4)),
]

In [8]:
# The cost data is made into a dictionary
costs = makeDict([Depots,lpg_customers_nodes],costs,0)

In [24]:
# Creates the 'prob' variable to contain the problem data
prob = LpProblem("LPG Delivery Scheduling",LpMinimize)

/usr/local/lib/python3.6/dist-packages/pulp/pulp.py:1199: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

In [25]:
# Creates a list of tuples containing all the possible routes for transport
Routes = [(w,b) for w in Depots for b in lpg_customers_nodes]

In [26]:
# A dictionary called 'Vars' is created to contain the referenced variables(the routes)
vars = LpVariable.dicts("Route",(Depots,lpg_customers_nodes),0,None,LpInteger)

In [27]:
# The cost function is added to 'prob' first
prob += lpSum([vars[w][b]*costs[w][b] for (w,b) in Routes]), "Sum_of_Transporting_Costs"

In [28]:
# The supply maximum constraints are added to prob for each supply node (warehouse)
for w in Depots:
    prob += lpSum([vars[w][b] for b in lpg_customers_nodes])<=supply[w], "Sum_of_Products_out_of_Depots_%s"%w

# The demand minimum constraints are added to prob for each demand node (bar)
for b in lpg_customers_nodes:
    prob += lpSum([vars[w][b] for w in Depots])>=demand[b], "Sum_of_Products_into_Customer%s"%b

In [29]:
prob.solve()

1

In [36]:
optimal_solution={}
optimal_solution_name=[]
optimal_solution_value=[]
for v in prob.variables():
    if v.varValue is not None and v.varValue > 0:
        optimal_solution_name.append(v.name)
        optimal_solution_value.append(v.varValue)
        optimal_solution.update({v.name:v.varValue})

In [54]:
optimal_route_name=[]
optimal_customer=[]
locations_=[]
results=[]
for i in range(len(optimal_solution_name)):
#     optimal_route.update({optimal_solution_name[i][6:11]:optimal_solution_name[i][12:16]})
        if optimal_solution_name[i][6:11]==optimal_solution_name[i][6:11]:
            locations_.append(optilandia_locations[optilandia_locations['id']==int(optimal_solution_name[i][12:16])])
            optimal_route_name.append(optimal_solution_name[i][6:11])
            optimal_customer.append([optimal_solution_name[i][12:16],optimal_solution_value[i]])

for i in range(len(locations_)):
    results.append([optimal_solution_name[i][6:11],[[optimal_solution_name[i][12:16],-(locations_[i]['capacity']-locations_[i]['level'])]]])

In [55]:
df=pd.DataFrame(results,columns=['lorry_id','loc'])

In [56]:
solution=df.groupby("lorry_id").sum()

In [57]:
solution

                                                        loc
lorry_id
116_0                                      [[265, [-0.48]]]
116_1     [[130, [-1.19]], [177, [-1.23]], [210, [-0.47]...
124_0     [[100, [-1.02]], [235, [-0.36]], [543, [-0.54]...
124_1     [[118, [-0.71]], [202, [-0.17000000000000004]]...
124_2     [[183, [-0.3999999999999999]], [260, [-1.62]],...
124_3     [[113, [-0.44999999999999996]], [205, [-0.9099...
124_4     [[110, [-1.99]], [136, [-0.33999999999999997]]...
124_5     [[206, [-0.88]], [294, [-0.81]], [362, [-0.75]...
124_6                      [[220, [-0.61]], [446, [-0.94]]]
124_7     [[254, [-1.28]], [397, [-0.7]], [476, [-0.3100...
373_0     [[204, [-0.69]], [308, [-0.6799999999999999]],...
373_1     [[225, [-0.64]], [257, [-0.19999999999999996]]...
373_2     [[216, [-0.27]], [243, [-0.6699999999999999]],...
373_3     [[245, [-0.15000000000000002]], [271, [-0.9]],...
373_4      [[387, [-1.24]], [431, [-0.39]], [511, [-0.24]]]
373_5     [[190, [-0.3600000000000001]], [374, [-0.5]], ...
373_6       [[519, [-0.21000000000000002]], [606, [-1.44]]]
373_7     [[172, [-0.91]], [180, [-0.76]], [408, [-0.28]...
373_8     [[14, [-0.32999999999999996]], [411, [-0.99]],...
373_9     [[144, [-0.45999999999999996]], [169, [-1.4]],...
523_0     [[175, [-1.63]], [22, [-1.68]], [507, [-1.15]]...
523_1     [[200, [-0.27]], [276, [-0.9299999999999999]],...
523_2     [[103, [-0.43999999999999995]], [455, [-0.3]],...
523_3     [[13, [-0.19999999999999996]], [27, [-1.02]], ...
523_4     [[105, [-1.27]], [135, [-1.33]], [146, [-1.45]...

In [20]:
optilandia_example_sol

   lorry_id                                                loc
0     523-0                  [[523, 5], [70, -1.46], [523, 0]]
1     124-0  [[124, 5], [14, -0.33], [36, -0.81], [204, -0....
2     373-0                 [[373, 5], [270, -0.22], [373, 0]]
3     116-0                 [[116, 5], [398, -0.89], [116, 0]]
4     523-1    [[523, 5], [257, -0.2], [235, -0.36], [523, 0]]
5     124-1  [[124, 5], [542, -0.47000000000000003], [124, 0]]
6     373-1                 [[373, 5], [180, -0.76], [373, 0]]
7     116-1                              [[116, 12], [116, 0]]
8     523-2                              [[523, 12], [523, 0]]
9     124-2                               [[124, 5], [124, 0]]
10    373-2                               [[373, 5], [373, 0]]
11    523-3                              [[523, 12], [523, 0]]
12    124-3                              [[124, 12], [124, 0]]
13    373-3                              [[373, 12], [373, 0]]
14    523-4                              [[523, 22], [523, 0]]
15    124-4                              [[124, 12], [124, 0]]
16    373-4                              [[373, 12], [373, 0]]
17    124-5                              [[124, 12], [124, 0]]
18    373-5                              [[373, 12], [373, 0]]
19    124-6                              [[124, 22], [124, 0]]
20    373-6                              [[373, 12], [373, 0]]
21    124-7                              [[124, 22], [124, 0]]
22    373-7                              [[373, 22], [373, 0]]
23    373-8                              [[373, 22], [373, 0]]
24    373-9                              [[373, 22], [373, 0]]